### PR TITLE
Shen 21 updates

### PR DESCRIPTION
**Pull request by tizoc**
Small changes for #10. Incomplete because I'm still unsure about what to do with `exit`.

- Get rid of it
- Move it to another namespace?
- Other

@rkoeninger what do you think?

### CODE REVIEW

**Comment by tizoc** [comment]
There is also `*argv*` but I wouldn't touch that one (I didn't in Shen/Scheme) since it doesn't really cause any problem (`exit` in particular conflicts with a function of the same name in `provedit!`)

**Comment by rkoeninger** [comment]
@tizoc We could just call it `quit` instead, although I typically put non-standard functions in a port-specific namespace, which would make it `shen-cl.quit`.

`shen.*` for kernel functions
`shen-cl.*`, `shen-sharp.*`, etc. for port functions
`lisp.*`, `js.*`, `clr.*`, etc. for underlying platform functions

**Comment by tizoc** [comment]
@rkoeninger sounds good to me, `shen-cl.` prefix is it.

**Comment by tizoc** [comment]
@rkoeninger I named it `shen-cl.exit` instead of `shen-cl.quit` but only because `exit` is the usual name for such function in most (all I know) languages, but I have no strong feelings about the naming of this function either way, I can change it if you think `quit` is better than `exit`.

**Comment by rkoeninger** [comment]
@tizoc Is there anything else you want to get in this PR or is it good to go?

**Comment by tizoc** [comment]
@rkoeninger unless you have spotted any mistake or anything I have missed, it is good to go.

**Pull request merged**
